"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$character"
right_format = "$directory$git_branch$git_status"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold blue"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
